from __future__ import annotations

from collections.abc import Callable

def add(a: int, b: int) -> int: ...
def add_named(a: int, b: int, c: int | None = ...) -> int: ...
def add3(a: int, b: int, c: int | None = ...) -> int: ...
def bytes_len(data: bytes) -> int: ...
def call_twice(func: Callable[[int], int], x: int) -> int: ...
def dict_get(data: dict[str, int], key: str) -> int | None: ...
def divide(a: float, b: float) -> float: ...
def greet(name: str) -> str: ...
def is_even(n: int) -> bool: ...
def math_pi() -> float: ...
def maybe_tag(name: str) -> str | None: ...
def sum_list(values: list[int]) -> int: ...
def to_bytes(value: str) -> bytes: ...
def to_upper(value: str) -> str: ...

class Adder:
    def __init__(self) -> None: ...
    def add(self, a: int, b: int) -> int: ...
    def identity(self) -> Adder: ...

__all__: list[str]
