from __future__ import annotations

from typing import Any, Protocol

class SupportsRead(Protocol):
    def read(self, __size: int = ...) -> str | bytes: ...

class SupportsWrite(Protocol):
    def write(self, data: str) -> int: ...

def loads(data: str | bytes) -> Any: ...
def load(fp: SupportsRead) -> Any: ...
def dumps(value: Any) -> str: ...
def dump(value: Any, fp: SupportsWrite) -> None: ...
def to_python(data: str | bytes) -> Any: ...
def from_python(value: Any) -> str: ...

__all__: list[str]
