default:
    @just --list

fmt:
    ruff check --select I --fix
    ruff format
    zig fmt .

lint:
    zig fmt --check .
    zlint
    ruff check
    ty check

build:
    alloconda build --release

wheel: build
    rm -rf dist
    alloconda wheel-all --fetch
    alloconda inspect-lib zig-out/lib/*
    alloconda inspect --verify dist/*.whl

test:
    pytest -v tests

clean:
    rm -rf zig-out
    rm -rf dist
    rm zigzon/*.so
