def encode_varint(value: int) -> bytes: ...
def encode_varint_unsigned(value: int) -> bytes: ...
def decode_varint(data: bytes, offset: int) -> tuple[int, int]: ...
def make_tag(field_number: int, wire_type: int) -> int: ...
def parse_tag(tag: int) -> tuple[int, int]: ...
def zigzag_encode(value: int) -> int: ...
def zigzag_decode(value: int) -> int: ...
def encode_fixed32(value: int) -> bytes: ...
def encode_sfixed32(value: int) -> bytes: ...
def encode_fixed64(value: int) -> bytes: ...
def encode_sfixed64(value: int) -> bytes: ...
def encode_float(value: float) -> bytes: ...
def encode_double(value: float) -> bytes: ...
def decode_fixed32(data: bytes, offset: int) -> tuple[int, int]: ...
def decode_fixed64(data: bytes, offset: int) -> tuple[int, int]: ...
def float_from_bits(value: int) -> float: ...
def double_from_bits(value: int) -> float: ...

__all__: list[str]
