try:
    from collections.abc import Buffer  # type: ignore[unresolved-import]
except ImportError:
    Buffer = bytes | bytearray | memoryview

def encode_varint(value: int) -> bytes: ...
def encode_varint_unsigned(value: int) -> bytes: ...
def decode_varint(data: Buffer, offset: int) -> tuple[int, int]: ...
def make_tag(field_number: int, wire_type: int) -> int: ...
def parse_tag(tag: int) -> tuple[int, int]: ...
def zigzag_encode(value: int) -> int: ...
def zigzag_decode(value: int) -> int: ...
def encode_fixed32(value: int) -> bytes: ...
def encode_sfixed32(value: int) -> bytes: ...
def encode_fixed64(value: int) -> bytes: ...
def encode_sfixed64(value: int) -> bytes: ...
def encode_float(value: float) -> bytes: ...
def encode_double(value: float) -> bytes: ...
def encode_packed_int32s(values: list[int]) -> bytes: ...
def encode_packed_int64s(values: list[int]) -> bytes: ...
def encode_packed_uint32s(values: list[int]) -> bytes: ...
def encode_packed_uint64s(values: list[int]) -> bytes: ...
def encode_packed_sint32s(values: list[int]) -> bytes: ...
def encode_packed_sint64s(values: list[int]) -> bytes: ...
def encode_packed_bools(values: list[bool]) -> bytes: ...
def encode_packed_fixed32s(values: list[int]) -> bytes: ...
def encode_packed_sfixed32s(values: list[int]) -> bytes: ...
def encode_packed_floats(values: list[float]) -> bytes: ...
def encode_packed_fixed64s(values: list[int]) -> bytes: ...
def encode_packed_sfixed64s(values: list[int]) -> bytes: ...
def encode_packed_doubles(values: list[float]) -> bytes: ...
def decode_fixed32(data: Buffer, offset: int) -> tuple[int, int]: ...
def decode_fixed64(data: Buffer, offset: int) -> tuple[int, int]: ...
def skip_field(data: Buffer, offset: int) -> int | None: ...
def float_from_bits(value: int) -> float: ...
def double_from_bits(value: int) -> float: ...
def varint_to_int32(value: int) -> int: ...
def varint_to_int64(value: int) -> int: ...
def varint_to_uint32(value: int) -> int: ...
def varint_to_uint64(value: int) -> int: ...
def varint_to_sint32(value: int) -> int: ...
def varint_to_sint64(value: int) -> int: ...
def varint_to_bool(value: int) -> bool: ...
def fixed32_to_sfixed32(value: int) -> int: ...
def fixed64_to_sfixed64(value: int) -> int: ...
def decode_packed_int32s(data: Buffer) -> list[int]: ...
def decode_packed_int64s(data: Buffer) -> list[int]: ...
def decode_packed_uint32s(data: Buffer) -> list[int]: ...
def decode_packed_uint64s(data: Buffer) -> list[int]: ...
def decode_packed_sint32s(data: Buffer) -> list[int]: ...
def decode_packed_sint64s(data: Buffer) -> list[int]: ...
def decode_packed_bools(data: Buffer) -> list[bool]: ...
def decode_packed_fixed32s(data: Buffer) -> list[int]: ...
def decode_packed_sfixed32s(data: Buffer) -> list[int]: ...
def decode_packed_floats(data: Buffer) -> list[float]: ...
def decode_packed_fixed64s(data: Buffer) -> list[int]: ...
def decode_packed_sfixed64s(data: Buffer) -> list[int]: ...
def decode_packed_doubles(data: Buffer) -> list[float]: ...

__all__: list[str]
