import builtins

try:
    from collections.abc import Buffer  # type: ignore[unresolved-import]
except ImportError:
    Buffer = builtins.bytes | builtins.bytearray | memoryview

class Field:
    number: int
    wire_type: int

    def int32(self) -> int: ...
    def int64(self) -> int: ...
    def uint32(self) -> int: ...
    def uint64(self) -> int: ...
    def sint32(self) -> int: ...
    def sint64(self) -> int: ...
    def bool(self) -> builtins.bool: ...
    def enum(self) -> int: ...
    def fixed64(self) -> int: ...
    def sfixed64(self) -> int: ...
    def double(self) -> builtins.float: ...
    def fixed32(self) -> int: ...
    def sfixed32(self) -> int: ...
    def float(self) -> builtins.float: ...
    def string(self) -> str: ...
    def bytes(self) -> builtins.bytes: ...
    def message_data(self) -> builtins.bytes: ...
    def message(self) -> Reader: ...
    def packed_int32s(self) -> list[int]: ...
    def packed_int64s(self) -> list[int]: ...
    def packed_uint32s(self) -> list[int]: ...
    def packed_uint64s(self) -> list[int]: ...
    def packed_sint32s(self) -> list[int]: ...
    def packed_sint64s(self) -> list[int]: ...
    def packed_bools(self) -> list[builtins.bool]: ...
    def packed_fixed32s(self) -> list[int]: ...
    def packed_sfixed32s(self) -> list[int]: ...
    def packed_floats(self) -> list[builtins.float]: ...
    def packed_fixed64s(self) -> list[int]: ...
    def packed_sfixed64s(self) -> list[int]: ...
    def packed_doubles(self) -> list[builtins.float]: ...

class Reader:
    def __init__(self, data: Buffer) -> None: ...
    def __iter__(self) -> Reader: ...
    def __next__(self) -> Field: ...
    def next_field(self) -> Field | None: ...
    def skip(self) -> bool: ...
    def remaining(self) -> int: ...

class Writer:
    def __init__(
        self, parent: Writer | None = None, field_num: int | None = None
    ) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self, exc_type: object | None, exc_val: object | None, exc_tb: object | None
    ) -> builtins.bool: ...
    def int32(self, field_number: int, value: int) -> None: ...
    def int64(self, field_number: int, value: int) -> None: ...
    def uint32(self, field_number: int, value: int) -> None: ...
    def uint64(self, field_number: int, value: int) -> None: ...
    def sint32(self, field_number: int, value: int) -> None: ...
    def sint64(self, field_number: int, value: int) -> None: ...
    def bool(self, field_number: int, value: builtins.bool) -> None: ...
    def enum(self, field_number: int, value: int) -> None: ...
    def fixed64(self, field_number: int, value: int) -> None: ...
    def sfixed64(self, field_number: int, value: int) -> None: ...
    def double(self, field_number: int, value: builtins.float) -> None: ...
    def fixed32(self, field_number: int, value: int) -> None: ...
    def sfixed32(self, field_number: int, value: int) -> None: ...
    def float(self, field_number: int, value: builtins.float) -> None: ...
    def string(self, field_number: int, value: str) -> None: ...
    def bytes(self, field_number: int, value: Buffer) -> None: ...
    def message(self, field_number: int) -> Writer: ...
    def end(self) -> None: ...
    def packed_int32s(self, field_number: int, values: list[int]) -> None: ...
    def packed_int64s(self, field_number: int, values: list[int]) -> None: ...
    def packed_uint32s(self, field_number: int, values: list[int]) -> None: ...
    def packed_uint64s(self, field_number: int, values: list[int]) -> None: ...
    def packed_sint32s(self, field_number: int, values: list[int]) -> None: ...
    def packed_sint64s(self, field_number: int, values: list[int]) -> None: ...
    def packed_bools(self, field_number: int, values: list[builtins.bool]) -> None: ...
    def packed_fixed32s(self, field_number: int, values: list[int]) -> None: ...
    def packed_sfixed32s(self, field_number: int, values: list[int]) -> None: ...
    def packed_floats(
        self, field_number: int, values: list[builtins.float]
    ) -> None: ...
    def packed_fixed64s(self, field_number: int, values: list[int]) -> None: ...
    def packed_sfixed64s(self, field_number: int, values: list[int]) -> None: ...
    def packed_doubles(
        self, field_number: int, values: list[builtins.float]
    ) -> None: ...
    def finish(self) -> builtins.bytes: ...
    def clear(self) -> None: ...

__all__: list[str]
