ARG PYTHON_IMAGE=python:3.14-slim
FROM ${PYTHON_IMAGE}

WORKDIR /app
COPY ./*.whl /app/
COPY tests ./tests
COPY pyproject.toml ./pyproject.toml

RUN python -m pip install -v ./*.whl pytest

CMD ["pytest", "-v", "tests"]
