default:
    @just --list

fmt:
    ruff check --select I --fix
    ruff format

lint:
    ruff check
    ty check
    fd -e zig.j2 | zlint --stdin

test:
    pytest tests/

clean:
    rm -rf *.egg-info
